version: '3.9'
services:
  flowchart:
    build:
      context: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - host

  postgres:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5436:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - host

volumes:
  data:


networks:
  host:


